# Introdução

Boas vindas!

Este guia tem como objetivo descrever instruções para as pessoas que desejam contribuir com a tradução de conteúdos técnicos sobre R para Português Brasileiro (PT-BR).

Este guia está sendo desenvolvido para ser utilizado no [projeto de tradução colaborativa](https://github.com/cienciadedatos/pt-r4ds/wiki) do livro [R for Data Science](https://r4ds.had.co.nz/) para Português Brasileiro (PT-BR). Porém, esperamos que este guia seja útil para outros projetos de tradução de conteúdos técnicos sobre R para PT-BR.


Este guia foi inspirado no *[Proyecto de traducción colaborativa de "R para Ciencia de Datos"](https://github.com/cienciadedatos/documentacion-traduccion-r4ds)*, elaborado pela equipe que realizou a tradução da primeira edição do livro [R for Data Science](https://r4ds.had.co.nz/) para Espanhol.

Outro guia importante para a tradução de conteúdos técnicos sobre R para PT-BR é o [Guia de tradução do R Base](https://contributor.r-project.org/translations/Conventions_for_Languages/Brazilian%E2%80%90Portugese-specific-translations.html#glossary).
