# Participe de projetos de tradução/revisão

## Livro R for Data Science (R4DS)



O [projeto de tradução colaborativa](https://github.com/cienciadedatos/pt-r4ds/wiki) do livro [R for Data Science](https://r4ds.had.co.nz/) (R4DS) para Português Brasileiro (PT-BR) é coordenado por [Beatriz Milz](https://github.com/beatrizmilz).

Todos os capítulos estão traduzidos, e atualmente estão em fase de revisão.

Caso queira contribuir com a revisão de algum capítulo, recomendamos que leia [a página do guia sobre a revisão no GitHub](revisando-github.qmd).

Caso necessário, envie um email para a coordenadora da tradução - Beatriz Milz: [milz.bea@gmail.com](mailto:milz.bea@gmail.com).

### Capítulos que necessitam de revisão

> Atualizado em 07/05/2024.

- Seção: Seção do livro, em inglês.
- Capítulo: Nome original do arquivo.
- URL PR: acesso à Pull Request no GitHub. Por aqui, é possível realizar a revisão do capítulo.

```{r}
#| message: false
#| warning: false
#| echo: false
readr::read_csv("traducao-r4ds.csv") |>
  tidyr::pivot_longer(
    cols = -c(secao, ordem, capitulo, n_issue, n_pr),
    values_to = "github",
    names_to = "contribuicao"
  ) |>
  dplyr::mutate(
    contribuicao = dplyr::case_when(
      contribuicao == "traducao" ~ "Tradução",
      stringr::str_starts(contribuicao, pattern = "revisao") ~ "Revisão"
    ),
    url_issue = paste0(
      "https://github.com/cienciadedatos/pt-r4ds/issues/",
      n_issue
    ),
    url_pr = paste0("https://github.com/cienciadedatos/pt-r4ds/pull/", n_pr),
    url_pr = glue::glue("<a href='{url_pr}' target='_blank'>{url_pr}</a>")
  ) |>
  dplyr::filter(github == "???") |>
  dplyr::distinct(secao, capitulo, url_pr) |>
  reactable::reactable(
    pagination = FALSE,
    searchable = TRUE,
    columns = list(url_pr =  reactable::colDef(html = TRUE))
  )

```


